volumes:
  mongo-data:

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - .:/bak
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}

  chat-agent:
    build: ./agent
    depends_on:
      - mongo
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    profiles:
      - donotstart
    environment:
      - DATABASE_URL=mongodb://${DB_USER}:${DB_PASS}@mongo:27017/chat_database
    stdin_open: true  # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY
