volumes:
  mongo-data:

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - .:/bak
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
